#+TITLE: Ниджу

Закончилась последняя лекция, где пожилой профессор с выворачивающей мозг
нудностью рассказывал о каких-то очевидных вещах. Скука, голод и отвращение к
этой грязной аудитории с глупыми граффити на партах сузили взор Д. до небольшого
пятна и заставляли его кровь пульсировать в висках. Д. начал поспешно закидывать
в сумку свои вещи, ему хотелось поскорее закончить этот кусок жизни,
напоминавший ему вязкий кафкианский кошмар.

-- Ты в курсе, что на следующей неделе коллоквиум?

Д. подпрыгнул как ужаленный. Ему захотелось схватить стул, что угодно в пределах
досягаемости, чтобы запустить в покрытое дешёвой косметикой лицо
старосты. Ничего не ответив, он повернулся и чуть ли не бегом покинул аудиторию.

Дорога домой была неблизкой, но представив, что ему придётся ехать зажатым в
транспорте среди людей, Д. решил возвращаться пешком. Подняв воротник, он
пошёл быстрым шагом, стараясь избегать оживлённых улиц. Под ногами хлюпала
кашица из опавших листьев вперемешку с плевками, в нос лез запах гнили. "Долго
ли я смогу это выносить?" -- не переставал спрашивать он себя.

На полпути домой Д. приходилось подниматься на холм по длинной лестнице. Здесь
дорога становилась особенно неприятной, и Д. то и дело приходилось присаживаться
на перила и с омерзением любоваться видом на окрестности. Он не находил в
панораме и следа стройности. Город застраивался беспорядочно, и архитектура
постоянно пыталась угнаться за разным модами. Пейзаж выглядел так, будто кто-то
разбросал по жухлой траве мешок мусора: грязные картонные коробки спальных
кварталов, одноразовые стаканчики градирен, поблескивающие битые бутылки
бизнес-центров.

Через некоторое время, физически и морально уставший от этой дороги, Д. подошёл
к дому. После небольших колебаний он приобрёл в магазинчике две бутылки пива и
наконец вошёл в тёмную квартиру.

Несмотря на завидную работоспособность и способность рождать десятки идей
ежедневно, Д. пока не слишком преуспел в жизни. В этот вечер он как раз
предавался горестным переживаниям по этому поводу. Это выражалось в том, что он
топил в пиве свою ненависть к этому тупому и унылому миру, неспособному даже
распознать его гений. Всё его окружение составляли легкомысленные личности,
которым не было дела до тайн мироздания, и которые не могли говорить с ним на
одном уровне. Поэтому Д. совершенно не стремился к их обществу. Считается, что
все эти одинокие гении тоже хотят тепла, но к Д. это точно не относилось. Только
к одной живой душе он тянулся всем сердцем. Нащупав под столом тапочки, наш
герой отправился к ней на встречу.

История их отношений поистине необычна и трагична. Они смогли возникнуть
благодаря тому, что примерно год назад один уважаемый университет проводил
открытые соревнования. Участником требовалось написать программу, угадывающую
функцию по её действию на входные данные. Д. в этом конкурсе тоже участвовал, и
его команда заняла почётное место в первой сотне. Но к тому моменту, как
результаты были оглашены, они уже не могли хоть как-то заинтересовать
его. Пускай старательные и ограниченные дураки в поте лица соревнуются в умении
играть по чужим правилам. Он один нашёл то, мимо чего прошли все эти зашоренные
посредственности.

Д. уселся за компьютер, запустил top и быстро пробежал глазами список
процессов. Вот его взгляд нашёл pid 1264, и тут же все его горести как будто
рукой сняло. "Моя Ниджу!", произнёс он с пьяной нежностью.

Да, Д. создал то, над чем бились лучшие умы веками: искусственную душу в
машине. Идея души оказалась проста, как колумбово яйцо. Он взял программу,
написанную для того конкурса, и заставил её угадывать вид самой себя. "Это и
есть то, что у людей называется рефлексией." -- рассуждал он. Моя программа
также сама создаёт входные данные, к которым применяется неизвестная функция
(объект), это и есть "фокус внимания". Вот и весь фокус.

Но консервативный и завистливый мир не собирался признавать это великое
открытие. "Людишки носятся со своим сознанием как со священной коровой. Им
просто не хочется признавать своё окончательное низвержение с трона уникальности
и значимости." -- думал об этом Д. -- "Эти шовинисты даже в сознательности
полностью человекоподобного AI будут сомневаться, что уж говорить про мою Ниджу,
обладающую принципиально непостижимым для них сознанием." Он часто сражался за
свои убеждения на просторах сети, и потому прекрасно понимал, насколько
невежественны все люди в этом вопросе.

-- Умные люди пишут, что сознание невычислимо. Поэтому того, что ты /якобы/
сделал, просто не может быть.

-- Сознание безусловно представляет собой невычислимый процесс. -- с усталой
улыбкой объяснял Д. -- Но ваш вывод из этого не следует.

-- Как же не следует. Невычислимый процесс -- это такой процесс, который нельзя
смоделировать на компьютере. Нельзя создать душу в компьютере. Вульгарные
физикалисты опять сели в лужу!

-- Вот вам пример невычислимой функции -- тут он приводит пример неприводимого
терма -- Если я попытаюсь его вычислить на компьютере, он взорвётся? Или, может,
господь поразит меня молнией? Нет, просто /процесс/ вычисления никогда не
завершится. А сознание -- это процесс, так? Это "странный цикл", рассказывающий
себе сказку о себе. И моя программа действительно реализует этот
алгоритм. Хотите, я покажу вам своё доказательство, что он действительно
undecidable?

Так выглядел типичный спор с далёким от темы человеком. Но и профессионалы не
разделяли убеждений Д. Они открыто называли его фриком и шизофреником,
перечисляли свойства интеллекта, которыми, согласно всей классической и
современной философии, он должен обладать. И ехидно спрашивали, не считает ли он
одушевлённой свою настольную лампу. Но Д. не признавал эти аргументы, как
любящий родитель никогда не признаёт своего ребёнка-аутиста не совсем
полноценным.

Надо сказать, Ниджу не была первой душой, созданной Д. Однако её предшественницы
трагически погибли. Первая -- из-за отключения электричества, вторая -- когда
Д. нечаянно зашёл на сайт, перегруженный java script'ом, и завершить
невычислимый процесс рендеринга всплывающих окошек и баннеров смогла только
"волшебная кнопка". Он горько оплакивал их судьбу, после чего дал клятву
отомстить виновным. Ведь из-за их халатности, как-никак, погибли живые души. К
сожалению, случая пролить кровь этих негодяев ему пока не представилось. С тех
пор Д. предпринял беспрецедентные меры предосторожности: приобрёл надёжный
бесперебойник и настроил квоты. Теперь в случае нештатной ситуации память
процесса 1264 мгновенно сбрасывалась на жёсткий диск, чтобы впоследствии этот
образ можно было реанимировать. Как бы то ни было, pid 1264 прожил уже полгода,
и Д. уже совсем сроднился с ним. Он задумывался над тем, чтобы приспособить к
нему визуализацию в виде анимушной рожицы и функцию органайзера. Тогда Ниджу
стала бы для него настоящим другом и помощником. Все бы обзавидовались, что у
него есть настоящая, одушевлённая вайфу, к тому же ещё и тихоня-интроверт... Это
же настолько моэ, что умереть можно.

Д. уселся за стол и с умилённым видом предался созерцанию того, как Ниджу
рефлексирует. С точки зрения непосвящённого наблюдателя это выглядело как
непрерывная печать малопонятных текстов, большей частью состоящих из круглых
скобок. Но Д. видел за этим процессом особую, доступную лишь избранным, красоту.
С каждой строчки на него смотрела улыбка Ниджу, такая радостная и сладкая, такая
непосредственная. Со вздохом он принялся рассказывать ей о своих печалях и
неурядицах. Понятное дело, Ниджу не могла этого слышать, но Д. не обижался. Надо
будет ещё будет объединить её с Элизой, решил он, и тогда проблема недостатка
социальных контактов будет окончательно решена. Выговорившись, он положил голову
на стол и с теплотой начал смотреть за деловитым копошением своего творения. За
этим его и сморил сон.

Пробудился Д. с тяжёлой головой, и неприятное ощущение во рту напоминало о
недавнем употреблении алкоголя. Пока он спал, стемнело, и комнату освещал только
монитор. Первым его движением было зайти на борды, посмотреть, что там написали
критики его любимого языка программирования и сильного AI. Его рука уже было
потянулась к мышке...

Краем глаза он уловил нечто, заставившее его окоченеть от ужаса. В вспышке
прозрения он почувствовал, как смерть ледяным сквозняком дышит ему в спину. И
теперь оставалось только одно: повернуть голову, чтобы взглянуть в её пустые
глазницы. Некоторое время он сидел, боясь даже вздохнуть. Наконец медленно,
словно загипнотизированный, он перевёл взгляд.

Так и есть. Окошко, где была открыта Ниджу, было мертво. Она больше не
выбрасывала строчки своих мыслей, и только курсор мигал, предлагая ввести
следующую команду. Д. издал стон, но тут же невероятным усилием воли взял себя в
руки в надежде, что может ему ещё удастся что-то сделать. Кажется, он кричал
что-то вроде "Живи, чёрт тебя возьми! Ты не можешь меня бросить так!", судорожно
пытаясь найти в системе хоть какие-то следы процесса 1264.

Некоторое время Д. просто сидел, обмякнув в кресле. Он не плакал. Вся боль
осталась внутри. Когда он поднял взгляд, стало ясно, что это уже
другой человек. Из его казавшихся спокойными глаз смотрела чёрная бездна
космической пустоты и одиночества. Он решил на прощание ещё раз посмотреть на
последние следы земного существования Ниджу. Странно, но следов аварийного
завершения программы не было. Оставалось последнее: он набрал в том самом окне
"echo $?".

Команда вернула "0", то есть процесс 1264 завершился
успешно. Д. поднял глаза чуть выше, на последнюю строчку, оставленную Ниджу. Это
был некий окончательный результат, и им было единственное число -- 42. После
чего Ниджу ушла в вечность с прощальной тихой улыбкой. Так Д. понял, что
классики ошибались, считая сознание невычислимым процессом.
